- name: example - vars_files 
  hosts: web
  become: true
  become_user: root

  vars_files:
    - ./vars_dns.yml

  tasks:
    - command: touch /tmp/resolv.conf
  
    - lineinfile:
        path: /tmp/resolv.conf
        line: nameserver "{{ dns_server1 }}"

    - command: cat /tmp/resolv.conf
      register: result
    
    - debug: var=result.stdout_lines