- name: example - vars_files 
  hosts: web
  become: true
  become_user: root

  vars_files:
    - ./vars_dns.yml

  tasks:
    - lineinfile:
        path: /etc/resolv.conf
        line: nameserver "{{ dns_server1 }}"